aissemble-pipeline-invocation-chart:
  app:
    name: "pipeline-invocation-service1"
  aissemble-quarkus-chart:
    image:
      imagePullPolicy: IfNotPresent
    service:
      type: NodePort
      ports:
        - name: "invocation-rest"
          port: 8080
          targetPort: 8080
          nodePort: 30005
        - name: "quarkus-managed"
          port: 9001
          targetPort: 9000
    ingress:
      enabled: false
